FROM node:lts-alpine

WORKDIR /usr/src/app

# Make puppeteer work in Docker
# https://github.com/puppeteer/puppeteer/issues/3994
RUN apk add --no-cache udev ttf-freefont chromium git
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ENV CHROMIUM_PATH /usr/bin/chromium-browser

COPY package* ./

RUN npm install

CMD ["npm", "run", "docker:dev"]